def complement(string):
	complementString = ""
	for p in string:
		if p == "C":
			complementString +="G"
		elif p == "G":
			complementString+="C"
		elif p == "A":
			complementString+="T"
		elif p == "T":
			complementString+="A"

	return(complementString[::-1])


string = "TGTGAAACTCTCATCGCCCGCGAGCCATACAGGATCTCCGCGCCTATTGACTATCGGTTCTATACTAAGCGAGCAGTATACAGGCGCGTTCGGCTGTATTTAGAACACACGACGAGAACACATCCCGAATGGGTTGGAACCATGTTGTGGTATGGAACTTGAGTAAGACAATGGAGACGAGACTTACACGTCCGAGCTTGCAAGTGGTGCAATGCCGAACTAACCACCCGCAGTTCCAAGTTAGTAAGGCGATATTTTAAACCTACGTCTCTTCAGGAAGCCCCTCCGGGGAGGGGTACCCTGTCATACCTTCCTTATAGTGAATAGCTTGGAATTACGATTTGAGGACCATTTAGAGGGCCTCCTTCACTGCCGAGAGAAGGGCTTTCAACGAAACTAAACAACTTCCATGAGTATCTATCTTGCCTAAATGACTCCTCAAATGACAGTACAGCCATGATGCCTCAGGCGACACAGATAACGAACACTATCCCGAATGCTGGGACCAAGCAGTACTTCAACTACCCTCTTCATGCGGCAGAGCCCATGCTACTGCTTAGAATAGAGTAGAACCGTGTTGAGTCAGATCGTAAGTGCTAGTACTCGAGTGTGGGACCAGAATGCGGGTGATATGTCGACAACCTCCGAGGAAGAGTCGCTGACAGCAGTCTCTTTTGAGCTGACAAGTCCGCAGTGCACCTCCCTGGGTCGTCGAGGTGAGTGGCACCACGAGGATGCTCAGCACCTAGCGGTCATGCTCTCTACGAGACTAGGCCCCCCAACAACACTTCAGCTAGAAACTGGGCTGTCATGTCGT"

print(complement(string))

